### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by stemangiola**

### CODE REVIEW

**Comment by mblue9** [comment]
I've added the newer actions here so you can test against R 4.1 & Bioc 3.13

**Comment by mblue9** [comment]
FYI the Mac error here is due to homebrew & looks like we have to just wait for a fix, reported here https://github.com/r-lib/actions/issues/280
The Linux & Windows errors are tidybulk-related I think.

**Comment by stemangiola** [comment]
> The Linux & Windows errors are tidybulk-related I think.

Thanks. Sorry I have not extensive tests of tidybulk for SE, I am a bit overwhelmed at the moment.

The tests would have avoided this whole wrong reduce dimension behaviour.

**Comment by stemangiola** [comment]
> > The Linux & Windows errors are tidybulk-related I think.
> 
> Thanks. Sorry I have not extensive tests of tidybulk for SE, I am a bit overwhelmed at the moment.
> 
> The tests would have avoided this whole wrong reduce dimension behaviour.

I have fixed few things, now vignette is failing because of the introduction of `feature`. Is tidybulk being checked against 3_13?

**Comment by mblue9** [comment]
>Thanks. Sorry I have not extensive tests of tidybulk for SE, I am a bit overwhelmed at the moment.

>The tests would have avoided this whole wrong reduce dimension behaviour.

No worries, totally understand!

>I have fixed few things, now vignette is failing because of the introduction of feature. Is tidybulk being checked against 3_13?

Yes definitely being checked against 3.13, can see in the actions here
Screen Shot 2021-04-13 at 8 21 40 am

I think it's because it's using tidySumarizedExperiment version 1.1.3 and feature is in 1.1.4?
Screen Shot 2021-04-13 at 8 21 09 am

As it's pulling from Bioc devel which only has 1.1.3
https://www.bioconductor.org/packages/devel/bioc/html/tidySummarizedExperiment.html

**Comment by stemangiola** [comment]
> I think it's because it's using tidySumarizedExperiment version 1.1.3 and feature is in 1.1.4?

True. I pushed the version 1.1.4 couple of days ago. Anyway now I pushed the 1.1.5. It should be online in couple of days.

Getting there!

**Comment by stemangiola** [comment]
> > I think it's because it's using tidySumarizedExperiment version 1.1.3 and feature is in 1.1.4?
> 
> True. I pushed the version 1.1.4 couple of days ago. Anyway now I pushed the 1.1.5. It should be online in couple of days.
> 
> Getting there!

In the website

https://www.bioconductor.org/packages/devel/bioc/html/tidySummarizedExperiment.html

I can see

image

**Comment by mblue9** [comment]
That's what I see too 1.1.3 in devel but we need 1.1.4 or 1.1.5 to appear there. Did you push to bioconductor repo? Their build report from Monday is showing it's still 1.1.3 https://www.bioconductor.org/checkResults/3.13/bioc-LATEST/#T

**Comment by stemangiola** [comment]
> Did you push to bioconductor repo?

I did for 1.1.4

**Comment by mblue9** [comment]
1.1.5 is there now https://www.bioconductor.org/packages/devel/bioc/html/tidySummarizedExperiment.html
so I’ve restarted the jobs here

**Comment by stemangiola** [comment]
> 1.1.5 is there now https://www.bioconductor.org/packages/devel/bioc/html/tidySummarizedExperiment.html
> so I’ve restarted the jobs here

Now locally checks pass, but here I get

```
Warning in tools::parse_Rd(infile) :
  /tmp/RtmpEjiKR1/filec9e04525abd5/tidybulk/man/keep_abundant-methods.Rd:105: unknown macro '\lifecycle'
    * ERROR: Avoid references to external hosting platforms
      Found in files:
        functions.R (line 2434, column 50)
```

I can't understand why, I have redone the lifecycle import..

**Comment by mblue9** [comment]
>Warning in tools::parse_Rd(infile) :
  /tmp/RtmpEjiKR1/filec9e04525abd5/tidybulk/man/keep_abundant-methods.Rd:105: unknown macro '\lifecycle'
    * ERROR: Avoid references to external hosting platforms
      Found in files:
        functions.R (line 2434, column 50)
>I can't understand why, I have redone the lifecycle import..

It's not due to lifecycle that's just a warning. It was this line 2434

`if("EPIC" %in% .packages() %>% not) stop("tidybulk says: Please attach the apckage EPIC manually (i.e. library(EPIC)). This is because EPIC is only available on GitHub and it is not possible to seemlessy make EPIC part of the dependencies.")`

Seems to be mention of Github triggers the error from this new check https://github.com/Bioconductor/BiocCheck/commit/60cef89407be43f420f97ba85c7cb23d5718a999#diff-6cd987920443d42098a4963d43b2e0efec9fd16f9198d66705e6d95094e3b87a

**Comment by mblue9** [comment]
I've edited that line to remove the mention of Github to see if it passes here.

**Comment by stemangiola** [comment]
Yeeeee

**Comment by mblue9** [comment]
Woo hoo 🎉finally 😅

**Pull request merged**
