### PR TITLE
Add refs

### PR DESCRIPTION
**Pull request by mblue9**
I added some refs here if you want them for voom, edger test methods, epic, llsr, ggplot2. 
Guess tidyheatmap can't be added as tidybulk doesn't use it under the hood?

### CODE REVIEW

**Comment by stemangiola** [comment]
Cool, I need to intercept this pull request to add the track of those reference in the methods as well (unless you know how to do it).

e.g.

image

But if you prefer to not go as deep I can do it no prob.



> Guess tidyheatmap can't be added as tidybulk doesn't use it under the hood?

I though about that XD, we could build a wrapper for tidyHeatmap, so to be able to call it without specifying sample, transcript, count (as we do for any other method). But let's think about that whether it's overkill.

**Comment by mblue9** [comment]
I am happy to have a go at adding tomorrow but I'm not sure everywhere they need to be added so you will need to check 😄

**Comment by mblue9** [comment]
Ok tried to add, could you check when you can.

**Comment by stemangiola** [comment]
> 
> 
> Ok tried to add, could you check when you can.

Looks good to me! For deconvolution you brought inside the `when` assignments, it should work.

Have to tested by any chance whether the bibliography is ultimately what you expect?

**Review by stemangiola — APPROVED** [review]

**Comment by stemangiola** [comment]
If I manage I might push this change into the new Bioconductor release (going public today)

**Comment by mblue9** [comment]
I'll have a look at testing this now...

**Comment by mblue9** [comment]
Tested running the DE methods separately and together and the refs seem to get added fine. 

But get_bibliography does not work with the changes here to the deconvolution methods e.g.
```
 > get_bibliography(epic_res)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘get_bibliography’ for signature ‘"tbl_df"’
```
But it doesn't seem like it worked before these changes for the deconvolution methods as installing tidybulk from Bioc devel (v 1.1.9) I get same error with method = "get", is only supposed to work with method="add"?

```
> BRCA_tidy <-
  BRCA %>%
   tidybulk(patient, transcript, count)
> res <- BRCA_tidy %>%
  deconvolve_cellularity(action="get", cores=2)
> get_bibliography(res)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘get_bibliography’ for signature ‘"tbl_df"’
```

Using method="add"
```
> res <- BRCA_tidy %>%
   deconvolve_cellularity(cores=2)
> get_bibliography(res)

@article{wickham2019welcome,
  title={Welcome to the Tidyverse},
  author={Wickham, Hadley and Averick, Mara and Bryan, Jennifer and Chang, Winston and McGowan, Lucy D'Agostino and Francois, Romain and Grolemund, Garrett and Hayes, Alex and Henry, Lionel and Hester, Jim and others},
  journal={Journal of Open Source Software},
  volume={4},
  number={43},
  pages={1686},
  year={2019}
	}
```

Cibersort ref is not added.

**Comment by stemangiola** [comment]
> is only supposed to work with method="add"?

No. I will have a look.

**Comment by stemangiola** [comment]
> is only supposed to work with method="add"

Yes. Because when we do get we get back a normal tibble, as is not anymore a compliant full dataset. I will make a clear error message.

This makes me think that I shoud print a message as I do for tidySE and tidySCE when a normal tibble is returned.

When tidySE will be part of tidybulk, this will be much simple.

**Comment by stemangiola** [comment]
Ups the branch is remote.

Can I ask to add a method for `tbl` class and print something like 

```
stop("tidybulk says: bibliography can be produced from a tidybulk tibble, not a regular tibble. Did you use action = \"get\", or pivot_transcript/pivot_sample?")

```

**Pull request merged**
