### PR TITLE
Use new version of biocthis github actions

### PR DESCRIPTION
**Pull request by mblue9**

### CODE REVIEW

**Comment by mblue9** [comment]
For the errors here the issue is R-devel and so I asked for advice from the author of the Github actions workflow [here](https://github.com/lcolladotor/biocthis/issues/15) 

>Ultimately, right now the issue is that Bioc-devel (3.13) runs on R-devel (what will become R 4.1) and CRAN does not provide binaries for packages on R-devel meaning that everything has to be compiled on macOS and Windows, which can be a bit painful. If what you are testing is not really that dependent on BioC 3.13 or R-devel, you could instead test using BioC 3.12 (bioc-release, R 4.0 which CRAN has binaries for the packages) for quick tests while Bioconductor will run the tests on Bioc 3.13 and figure out the compilation issues. Having said that, it can be a learning experience to figure out the compilation issues yourself.

What is your preference? Do you want to stick with testing here against R-devel & Bioc devel and we try to fix the compilation errors?

**Comment by stemangiola** [comment]
> For the errors here the issue is R-devel and so I asked for advice from the author of the Github actions workflow [here](https://github.com/lcolladotor/biocthis/issues/15)
> 
> > Ultimately, right now the issue is that Bioc-devel (3.13) runs on R-devel (what will become R 4.1) and CRAN does not provide binaries for packages on R-devel meaning that everything has to be compiled on macOS and Windows, which can be a bit painful. If what you are testing is not really that dependent on BioC 3.13 or R-devel, you could instead test using BioC 3.12 (bioc-release, R 4.0 which CRAN has binaries for the packages) for quick tests while Bioconductor will run the tests on Bioc 3.13 and figure out the compilation issues. Having said that, it can be a learning experience to figure out the compilation issues yourself.
> 
> What is your preference? Do you want to stick with testing here against R-devel & Bioc devel and we try to fix the compilation errors?

I would like to test with what does not gives issues already (like before). It is better we invest time on other things rather than testing on bug-prone invironment. Let's wait other people solve this issue first, than we can test when the system will be stable.

**Comment by mblue9** [comment]
Ok I can switch to test against Bioc release and R release.  When we started testing here we were using Bioc devel April-Oct which uses R release (so less issues) whereas [Bioc devel Oct-Apr uses R-deve](https://www.bioconductor.org/developers/how-to/useDevel/)l. Just note that it'll mean that when you push to Bioc devel there may be new issues in the build report that we didn't see here because we're testing against release but assume you won't be pushing there too frequently & Bioc may be able to help solve.

**Comment by stemangiola** [comment]
> Ok I can switch to test against Bioc release and R release. When we started testing here we were using Bioc devel April-Oct which uses R release (so less issues) whereas [Bioc devel Oct-Apr uses R-deve](https://www.bioconductor.org/developers/how-to/useDevel/)l. Just note that it'll mean that when you push to Bioc devel there may be new issues in the build report that we didn't see here because we're testing against release but assume you won't be pushing there too frequently & Bioc may be able to help solve.

That's correct. If I psh on devel they will do their tests, and I will fix based on those. When github actions will be fixed I assume we can switch to devel. 

But for the moment let's do the simple thing.

**Comment by stemangiola** [comment]
You are becoming quite an expert in Github actions! Is such complex system (although powerful).

**Comment by stemangiola** [comment]
Amazing! can I merge?

**Comment by mblue9** [comment]
Yes we're all good now (til next time 😄)

**Pull request merged**
