### PR TITLE
treat enhancements

### PR DESCRIPTION
**Pull request by mblue9**
I added the treat method for voom here & fixed a bug with edgeR treat multiple contrasts.
See if you think it's ok.
I edited functions.R & methods.R, does the code need to also be added to functions_SE.R & methods_SE.R ?

### CODE REVIEW

**Comment by stemangiola** [comment]
> I added the treat method for voom here & fixed a bug with edgeR treat multiple contrasts.
> See if you think it's ok.
> I edited functions.R & methods.R, does the code need to also be added to functions_SE.R & methods_SE.R ?

Amazing! Yes we need to do some duplicated work for _SE files but it is generally simpler than for tibble-based method.

**Comment by mblue9** [comment]
>Amazing! Yes we need to do some duplicated work for _SE files but it is generally simpler than for tibble-based method.

Ok done.

**Comment by stemangiola** [comment]
> > Amazing! Yes we need to do some duplicated work for _SE files but it is generally simpler than for tibble-based method.
> 
> Ok done.

Can I merge?

**Comment by mblue9** [comment]
Yep I’m done here, if you’re happy with it go for it.

**Pull request merged**
