### PR TITLE
Using man/fragments to share vignette and README

### PR DESCRIPTION
**Pull request by mblue9**
This has the vignette and README shared trick. It will fail with BiocCheck but just want to confirm here.

### CODE REVIEW

**Comment by stemangiola** [comment]
> 
> 
> This has the vignette and README shared trick. It will fail with BiocCheck but just want to confirm here.

Just to understand. What is the reason why Bioc does not like it?

**Comment by mblue9** [comment]
I don't know what exactly it doesn't like. I think it might be the "child" 

`{r child="man/fragments/intro.Rmd"}`

This is the error (pretty vague) `Error in file(con, "r") : cannot open the connection` 

I got it here with tidySCE https://github.com/stemangiola/tidySCE/runs/1084773143?check_suite_focus=true and also when trying the method with tidybulk locally.

**Comment by stemangiola** [comment]
> 
> 
> I don't know what exactly it doesn't like. I think it might be the "child"
> 
> `{r child="man/fragments/intro.Rmd"}`
> 
> This is the error (pretty vague) `Error in file(con, "r") : cannot open the connection`
> 
> I got it here with tidySCE https://github.com/stemangiola/tidySCE/runs/1084773143?check_suite_focus=true and also when trying the method with tidybulk locally.

If you feel would be helpful to write to the BioC mailing list, they are super active.

**Comment by mblue9** [comment]
Different issue but similar error  `Error in file(con, "r") : cannot open the connection` and it does seem to be related to the using child document in that case :
https://github.com/rstudio/learnr/issues/408

>If you feel would be helpful to write to the BioC mailing list, they are super active.

I was going to file an issue in the BioCheck repo as I think it's BiocCheck that will need modifying to get past the error. But do you think the mailing list is better?

**Comment by stemangiola** [comment]
> 
> 
> Different issue but similar error `Error in file(con, "r") : cannot open the connection` and it does seem to be related to the using child document in that case :
> [rstudio/learnr#408](https://github.com/rstudio/learnr/issues/408)
> 
> > If you feel would be helpful to write to the BioC mailing list, they are super active.
> 
> I was going to file an issue in the BioCheck repo as I think it's BiocCheck that will need modifying to get past the error. But do you think the mailing list is better?

I think is kind of the same. If you are confident that is that the problem, it makes sense.

**Comment by mblue9** [comment]
Yep in this case I'm 99% confident it's BiocCheck as it works fine with tidyseurat and R CMD Check. So I'll start with an issue there and see what they say. If we get it working we could let the mailing list know it's an option.

**Comment by stemangiola** [comment]
This seem to be failing for

```
checking dependencies in R code ... WARNING
  '::' or ':::' import not declared from: ‘EPIC’
```

Which I'm trying to fix in dev. Is is possible that your trick is actually working with Bioconductor?

**Comment by mblue9** [comment]
I still think it's Bioccheck but yes I saw that error here. Would be good to fix that first to make sure and before reporting to Bioccheck. Can you let me know here if you fix it and I'll test again? Or should I try this with another branch like master instead of dev?

**Comment by stemangiola** [comment]
This is wierd, I have fixed that error in dev and merged into master.

But yet, 

the error for this pull request is 

```
'::' or ':::' import not declared from: ‘EPIC’
```
Is like this pull request does not note the updated dev branch

**Comment by mblue9** [comment]
I tried the rebase but may have messed something up as there is the file connection error but also another one. I'll make a fresh branch off dev & a new PR and close this one.

**Comment by mblue9** [comment]
New PR is https://github.com/stemangiola/tidybulk/pull/111.

**Pull request closed without merging**
