### PR TITLE
test_gene_enrichment modifications

### PR DESCRIPTION
**Pull request by mblue9**
- Remove "all" as option in gene_collections xref https://github.com/stemangiola/tidybulk/issues/174#issuecomment-828014500
- Also adds gene_sets argument to allow custom gene sets through EGSEA's buildCustomIdx

### CODE REVIEW

**Comment by stemangiola** [comment]
Amazing. The only thing we should take a look at is that in the _SE version I am just using the "kegg" collection. Honestly, I didn't go too deep into understanding the three kegg_collection in which function they go.

```r
.test_gene_enrichment_SE = 		function(.data,
																			.formula,
																			.sample = NULL,
																			.entrez,
																			.abundance = NULL,
																			.contrasts = NULL,
																			method = c("camera" ,    "roast" ,     "safe",       "gage"  ,     "padog" ,     "globaltest",  "ora" ),
																			gene_collections = c("h" ,   "c1" ,  "c2" ,  "c3" ,  "c4" ,  "c5" ,  "c6"  , "c7" ,  "kegg"),
																			species,
																			cores = 10)	{
```

Probably is as easy as replacing "kegg" with your new "kegg_*" options.

**Comment by mblue9** [comment]
> Amazing. The only thing we should take a look at is that in the _SE version I am just using the "kegg" collection. Honestly, I didn't go too deep into understanding the three kegg_collection versus the "kegg" collection I am currently using.

Ok I've updated the SE function now to work the same as the tibble one and pushed here.

**Comment by mblue9** [comment]
I've added the ability to input custom gene sets to use with roast etc

Also noticed that there are no gene identifiers output in the "Interpret results" tables in the report so you can't easily see which row is for which gene. To fix can add the entrez gene ids to $genes slot in the DGEList here https://github.com/stemangiola/tidybulk/blob/5d59546074ffcad9442d9caf76d04e120aec5f2b/R/functions.R#L1285
I tried but I'm not sure how to get them in after the arrange step it e.g. edgeR::DGEList(counts = ., genes=!!entrez didn't work.

**Comment by stemangiola** [comment]
> I tried but I'm not sure how to get them in after the arrange step it e.g. edgeR::DGEList(counts = ., genes=!!entrez didn't work.

If you have SE object is easy rowData(entrez), if you have tibble you can do
```r
entrez_array = counts_df %>% distinct(!!feature, !!entrez) %>% arrange(!!featture %>% match(rownames(counts)))

edgeR::DGEList(counts = ., genes=entrez_array )
```

**Comment by mblue9** [comment]
Great thanks!

Could you eyeball what I've done 

especially this bit https://github.com/stemangiola/tidybulk/pull/176/files#diff-1914f62e1613797775065e47b0f506b7c62d4bc06fbb20ffd41707361d433209R1296

I added as_matrix there emporarily which gives a warning as the input isn't numeric. Reason I added it was to stop as.character in the egsea function turning the ids into one character, think due to the tidybulk tibble info, thought I could use as_data_frame but it didn't work. Do you know how that could be handled better?

**Comment by stemangiola** [comment]
> Great thanks!
> 
> Could you eyeball what I've done
> 
> especially this bit https://github.com/stemangiola/tidybulk/pull/176/files#diff-1914f62e1613797775065e47b0f506b7c62d4bc06fbb20ffd41707361d433209R1296
> 
> I added as_matrix there emporarily which gives a warning as the input isn't numeric. Reason I added it was to stop as.character in the egsea function turning the ids into one character, think due to the tidybulk tibble info, thought I could use as_data_frame but it didn't work. Do you know how that could be handled better?

What about something simpler? and if someone wants symbol they can add is afterwards manually.

```r
 dge$genes=rownames(dge$counts))
```

(btw the column name symbol is not fixed. It is quite hard to detect symbol-containing column)

**Comment by mblue9** [comment]
>(btw the column name symbol is not fixed. It is quite hard to detect symbol-containing column)

So I had set it up so the user could specify the symbol column, it wasn't relying on it being called symbol or detecting it but ..

>What about something simpler? and if someone wants symbol they can add is afterwards manually.

yes lets just keep it simple and do that for moment

**Comment by stemangiola** [comment]
Nice!

I would like to propose a design change. (I can do the coding no prob in case).

Generally speaking, I value the cost of adding function arguments very high. That's why I always try to arrange and merge things if similar.

For example, the way I would organise 

gene_collections
gene_sets 

is merge them is a more flexible container, a list.

gene_collections could be a list as such 

```gene_collections = list("c2", "kegg_disease", "my_gene_set" = c("11109", "34565", "24356")```

And in the backend, we subtract the defined collections from the custom collections, process the custom, and process altogether if possible or merge the results.

What do you think? The downside here is that the terms collection and set get a bit mixed up.

A way to harmonise this would be to require input collections

```gene_collections = list("c2", "kegg_disease", "my_gene_collection" = list( "my_gene_set_1" = c("11109", "34565", "24356"))) ```

I don't have a strong feeling for this, but would be nice to be creative and avoid additions of argument when possible. And I'm not saying this is necessary the case.

**Comment by mblue9** [comment]
I think that's a good idea to try to combine them, I did wonder if it might be better to do that. 
What about we try it and should we call it gene_sets instead of gene_collections? As I think "collections" is more specific to msigdb and gene_sets the more common general term.
If you don't mind having a go at the code would be great as I think you'd be quicker than me!

**Comment by stemangiola** [comment]
> I think that's a good idea to try to combine them, I did wonder if it might be better to do that.
> What about we try it and should we call it gene_sets instead of gene_collections? As I think "collections" may be more specific to msigdb and gene_sets the more common general term. But probably either is fine.

I agree on gene_sets, as a gene collection is "gene_sets" and many gene collections are still "gene_sets".

> If you don't mind having a go at the code would be great as I think you'd be quicker than me!

I am a bit struggling at the moment, but I can approach it when I am quieter. I lost a bit of grip with the whole custom vs collection signatures :)

**Comment by mblue9** [comment]
>I am a bit struggling at the moment, but I can approach it when I am quieter. I lost a bit of grip with the whole custom vs collection signatures :)

No worries if I can get to it before you I'll do it.

**Comment by mblue9** [comment]
Ok what do you think of what I've pushed here. Turns out can only use the custom sets if not using the collections (unless there's some way to combine the egsea objects). So as egsea expects either a character vector of collections or a list of custom sets this checks if the gene_sets argument is a list, if so runs the custom sets, if not, checks for the collections. Or is that too messy?

**Comment by stemangiola** [comment]
> Ok what do you think of what I've pushed here. Turns out can only use the custom sets if not using the collections (unless there's some way to combine the egsea idx objects). So as egsea expects either a character vector of collections or a list of custom sets this checks if the gene_sets argument is a list, if so runs the custom sets, if not, checks for the collections. Or is that too messy?

I see :). OK I think is a OK design, especially because 99% of users will use default gene sets. I think checking for class==list is a bit dangerous, but let's keep it like this, and will can keep thinking about it for future releases.

Your have done a great job!

**Comment by stemangiola** [comment]
I hope I did not cause this error.

```
invalid class "Graph" object: superclass "Mnumeric" not defined in the environment of the object's class
   --- failed re-building ‘comparison_with_base_R.Rmd’
```

Seems unrelated to anything we did.

**Comment by mblue9** [comment]
It's not us :)

Seems to be due to an updated version of Matrix package (v1.3-3) being installed here https://github.com/stemangiola/tidybulk/runs/2500352392?check_suite_focus=true#step:15:569

As if I install that version locally I then get same error if try to run the code in comparison_with_base_R.Rmd.

Maybe something to do with this change in  https://cran.r-project.org/web/packages/Matrix/news.html
>removed the nowhere used (and unexported but still active) class union "Mnumeric" which actually trickled into many base classes properties. Notably would it break validity of factor with a proposed change in validity checking, as factors were also "Mnumeric" but did not fulfill its validity method.

is what's triggering the error with tidybulk. But I've no idea how to fix that.

**Comment by stemangiola** [comment]
> Seems to be due to an updated version of Matrix package (v1.3-3) being installed here

You see the crap with Bioconductor and CRAN, is that when things break in one does not get detected and fixed. If all packages were in CRAN if you break back compatibility you have to fix it, otherwise you cannot submit.

**Comment by stemangiola** [comment]
> > Seems to be due to an updated version of Matrix package (v1.3-3) being installed here
> 
> You see the crap with Bioconductor and CRAN, is that when things break in one does not get detected and fixed. If all packages were in CRAN if you break back compatibility you have to fix it, otherwise you cannot submit.

This is to do with Seurat. How come I don't see people posting this error on forums?

**Comment by stemangiola** [comment]
> It's not us :)
> 
> Seems to be due to an updated version of Matrix package (v1.3-3) being installed here https://github.com/stemangiola/tidybulk/runs/2500352392?check_suite_focus=true#step:15:569
> 
> As if I install that version locally I then get same error if try to run the code in comparison_with_base_R.Rmd.
> 
> Maybe something to do with this change in https://cran.r-project.org/web/packages/Matrix/news.html
> 
> > removed the nowhere used (and unexported but still active) class union "Mnumeric" which actually trickled into many base classes properties. Notably would it break validity of factor with a proposed change in validity checking, as factors were also "Mnumeric" but did not fulfill its validity method.
> 
> is what's triggering the error with tidybulk. But I've no idea how to fix that.

I have created a error message explaining the issue, and eliminated all SNN calls. Which are pretty rare at this stage. We should keep monitoring this bug, and rehabilitate it as soon as possible.

Can I merge? (great job putting this together!)

**Comment by mblue9** [comment]
Missed replying here, thanks for the merge!

>This is to do with Seurat. How come I don't see people posting this error on forums?

Seems it's been reported a few times over the last few days in the Seurat repo e.g. https://github.com/satijalab/seurat/issues/4436 That issue's closed as it has a workaround to downgrade to matrix 1.3-2 but that won't help packages that have Seurat as a dependency will it? 

Matrix and Seurat are both in CRAN so how come Matrix didn't have to deal with the back compatibility? Is it because Matrix is an Import and not a Depends of Seurat?

**Comment by mblue9** [comment]
FYI https://github.com/mojaveazure/seurat-object/pull/11

**Comment by stemangiola** [comment]
That workaround iS not really a solution.  In CRAN reverse dependecies
cannot be broken either. I'm not sure how often they are checked but Matrix
should have been stopped before publication. Very weird.

**Pull request merged**
