### PR TITLE
Add egsea to bibliography

### PR DESCRIPTION
**Pull request by mblue9**

### CODE REVIEW

**Comment by stemangiola** [comment]
It would be amazing to add misgdb and the single methods too. But yeah egsea is the base.

I though I had it already..

**Comment by mblue9** [comment]
Good idea, I've added the refs for the other methods and the collections here.

**Comment by mblue9** [comment]
I don't know if this is the right way to deal with the cedilla character - ç in François
`author = {Di Wu and Elgene Lim and Fran\u0037ois Vaillant and Marie-Liesse Asselin-Labat and Jane E. Visvader and Gordon K. Smyth},`

to fix the error

```
❯ checking R files for non-ASCII characters ... WARNING
  Found the following file with non-ASCII characters:
    bibliography.R
  Portable packages must use only ASCII characters in their R code,
  except perhaps in comments.
  Use \uxxxx escapes for other characters.
```
Do you know?
Otherwise good to merge here.

**Comment by stemangiola** [comment]
I don't think it matters to preserve the original letters.

**Pull request merged**
