### PR TITLE
add framework

### PR DESCRIPTION
**Pull request by stemangiola**

### CODE REVIEW

**Comment by stemangiola** [comment]
@mblue9 github action is starting to get annoying

```
Error: Failed to get R 4.1: Failed to get R 4.1: Failed to download version 4.1: Error: Unexpected HTTP response: 404
```

Do you think we are doing something wrong in the action file? Before was all good.

**Comment by stemangiola** [comment]
Do you have any idea with this?

```
Failed to get R 4.1: Failed to get R 4.1: Failed to download version 4.1: Error: Unexpected HTTP response: 404
```

I can't find any 4.1 R dependency

**Comment by mblue9** [comment]
Sorry missed your first notification here. Bioc devel is now using R 4.1 and that seems to have broken the action but I've updated to use the current biocthis action here https://github.com/stemangiola/tidybulk/pull/135 which uses current release Bioc 3.12 & R 4.0 so lets see if that fixes it.

**Comment by stemangiola** [comment]
> Sorry missed your first notification here. Bioc devel is now using R 4.1 and that seems to have broken the action but I've updated to use the current biocthis action here #135 which uses current release Bioc 3.12 & R 4.0 so lets see if that fixes it.

So knowledgeable!

**Pull request merged**
