### PR TITLE
Sharing vignette and README

### PR DESCRIPTION
**Pull request by mblue9**
Take 2. This should be a clean fail at the BiocCheck step.

### CODE REVIEW

**Comment by stemangiola** [comment]
You Bioc error came up :(

**Comment by mblue9** [comment]
Yes and found the `child` issue was already reported for BiocCheck here https://github.com/Bioconductor/BiocCheck/issues/17

**Comment by mblue9** [comment]
Leaving this here for the moment as a reminder that this can't be added until BiocCheck is fixed to allow child docs (I might try that when I get time).

**Comment by stemangiola** [comment]
@mblue9 abemus papa! 

https://github.com/Bioconductor/BiocCheck/pull/121

**Comment by mblue9** [comment]
Superseded by #111

**Pull request closed without merging**
