### PR TITLE
Add voomWithQualityWeights method

### PR DESCRIPTION
**Pull request by mblue9**
I think this is what's needed to add the voom with sample weights method.

### CODE REVIEW

**Comment by stemangiola** [comment]
> 
> 
> I think this is what's needed to add the voom with sample weights method. I will complete review soon.

Boom! Amazing!

**Comment by mblue9** [comment]
Fixing the conflicts now. Also I called the method limma_voomWithQualityWeights  (similar to the original function name) but if you want something else like limma_voom_with_quality_weights let me know & I'll change it.

**Comment by stemangiola** [comment]
> 
> 
> Fixing the conflicts now. Also I called the method limma_voomWithQualityWeights (similar to the original function name) but if you want something else like limma_voom_with_quality_weights let me know & I'll change it.

What about `limma_voom_weights` or `limma_voom_weighted`?

**Comment by mblue9** [comment]
>What about limma_voom_weights or limma_voom_weighted?

regular voom calculates observational weights so maybe  `limma_voom_sample_weights`?

**Comment by stemangiola** [comment]
An important thing we have to do any time we add a new feature is to build unit tests (at least one) ;) I know nobody likes them! 

And possibly making them efficient in terms of computation. I haven't been the most diligent into building efficient tests, but I have built a lot of them in the directory test, and add yours. You can look for the voom method as example.

If you don't want to deal with tests I'll do no prob!

**Comment by mblue9** [comment]
Tests are good! 😄  happy to add them.

**Comment by stemangiola** [comment]
> 
> 
> Tests are good! 😄 happy to add them.

I was waiting for your unit tests, but I saw you already added them! I'll merge

**Pull request merged**
