### PR TITLE
Add LFC threshold tests for DESeq2

### PR DESCRIPTION
**Pull request by mikelove**
hi Stefano,

I've added examples and tests, and I tested locally to make sure that the bulk methods are still working.

I had already added in the ellipses, but I had forgotten one spot which is why it wasn't working, this PR should include all the necessary ellipses for limma and deseq2

### CODE REVIEW

**Comment by stemangiola** [comment]
@mikelove it seems an example is erroring

**Comment by mikelove** [comment]
I’ll fix this

**Comment by mikelove** [comment]
Ok this latest commit should fix things

**Comment by stemangiola** [comment]
> Ok this latest commit should fix things

Thanks a lot for your contribution, and welcome to the tidybulk team! ;)

**Comment by mikelove** [comment]
I have some ideas about exploring isoform-level abundance, especially within genes, do you have anything currently for this?

**Comment by stemangiola** [comment]
> I have some ideas about exploring isoform-level abundance, especially within genes, do you have anything currently for this?

Nope, you have carte blanche!

**Pull request merged**
